
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */


#ifndef pdf-to-html_ENUMS_H
#define pdf-to-html_ENUMS_H

#include <glib-object.h>

G_BEGIN_DECLS

/* enumerations from "pdf-to-html-action.h" */
GType pdf-to-html_action_type_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_ACTION_TYPE (pdf-to-html_action_type_get_type ())
GType pdf-to-html_dest_type_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_DEST_TYPE (pdf-to-html_dest_type_get_type ())
GType pdf-to-html_action_movie_operation_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_ACTION_MOVIE_OPERATION (pdf-to-html_action_movie_operation_get_type ())
GType pdf-to-html_action_layer_action_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_ACTION_LAYER_ACTION (pdf-to-html_action_layer_action_get_type ())

/* enumerations from "pdf-to-html-annot.h" */
GType pdf-to-html_annot_type_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_ANNOT_TYPE (pdf-to-html_annot_type_get_type ())
GType pdf-to-html_annot_flag_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_ANNOT_FLAG (pdf-to-html_annot_flag_get_type ())
GType pdf-to-html_annot_markup_reply_type_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_ANNOT_MARKUP_REPLY_TYPE (pdf-to-html_annot_markup_reply_type_get_type ())
GType pdf-to-html_annot_external_data_type_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_ANNOT_EXTERNAL_DATA_TYPE (pdf-to-html_annot_external_data_type_get_type ())
GType pdf-to-html_annot_text_state_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_ANNOT_TEXT_STATE (pdf-to-html_annot_text_state_get_type ())
GType pdf-to-html_annot_free_text_quadding_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_ANNOT_FREE_TEXT_QUADDING (pdf-to-html_annot_free_text_quadding_get_type ())

/* enumerations from "pdf-to-html-document.h" */
GType pdf-to-html_page_layout_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_PAGE_LAYOUT (pdf-to-html_page_layout_get_type ())
GType pdf-to-html_page_mode_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_PAGE_MODE (pdf-to-html_page_mode_get_type ())
GType pdf-to-html_font_type_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_FONT_TYPE (pdf-to-html_font_type_get_type ())
GType pdf-to-html_viewer_preferences_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_VIEWER_PREFERENCES (pdf-to-html_viewer_preferences_get_type ())
GType pdf-to-html_permissions_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_PERMISSIONS (pdf-to-html_permissions_get_type ())

/* enumerations from "pdf-to-html-form-field.h" */
GType pdf-to-html_form_field_type_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_FORM_FIELD_TYPE (pdf-to-html_form_field_type_get_type ())
GType pdf-to-html_form_button_type_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_FORM_BUTTON_TYPE (pdf-to-html_form_button_type_get_type ())
GType pdf-to-html_form_text_type_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_FORM_TEXT_TYPE (pdf-to-html_form_text_type_get_type ())
GType pdf-to-html_form_choice_type_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_FORM_CHOICE_TYPE (pdf-to-html_form_choice_type_get_type ())

/* enumerations from "pdf-to-html-movie.h" */
GType pdf-to-html_movie_play_mode_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_MOVIE_PLAY_MODE (pdf-to-html_movie_play_mode_get_type ())

/* enumerations from "pdf-to-html-structure-element.h" */
GType pdf-to-html_structure_element_kind_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_STRUCTURE_ELEMENT_KIND (pdf-to-html_structure_element_kind_get_type ())
GType pdf-to-html_structure_get_text_flags_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_STRUCTURE_GET_TEXT_FLAGS (pdf-to-html_structure_get_text_flags_get_type ())
GType pdf-to-html_structure_placement_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_STRUCTURE_PLACEMENT (pdf-to-html_structure_placement_get_type ())
GType pdf-to-html_structure_writing_mode_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_STRUCTURE_WRITING_MODE (pdf-to-html_structure_writing_mode_get_type ())
GType pdf-to-html_structure_border_style_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_STRUCTURE_BORDER_STYLE (pdf-to-html_structure_border_style_get_type ())
GType pdf-to-html_structure_text_align_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_STRUCTURE_TEXT_ALIGN (pdf-to-html_structure_text_align_get_type ())
GType pdf-to-html_structure_block_align_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_STRUCTURE_BLOCK_ALIGN (pdf-to-html_structure_block_align_get_type ())
GType pdf-to-html_structure_inline_align_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_STRUCTURE_INLINE_ALIGN (pdf-to-html_structure_inline_align_get_type ())
GType pdf-to-html_structure_text_decoration_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_STRUCTURE_TEXT_DECORATION (pdf-to-html_structure_text_decoration_get_type ())
GType pdf-to-html_structure_ruby_align_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_STRUCTURE_RUBY_ALIGN (pdf-to-html_structure_ruby_align_get_type ())
GType pdf-to-html_structure_ruby_position_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_STRUCTURE_RUBY_POSITION (pdf-to-html_structure_ruby_position_get_type ())
GType pdf-to-html_structure_glyph_orientation_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_STRUCTURE_GLYPH_ORIENTATION (pdf-to-html_structure_glyph_orientation_get_type ())
GType pdf-to-html_structure_list_numbering_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_STRUCTURE_LIST_NUMBERING (pdf-to-html_structure_list_numbering_get_type ())
GType pdf-to-html_structure_form_role_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_STRUCTURE_FORM_ROLE (pdf-to-html_structure_form_role_get_type ())
GType pdf-to-html_structure_form_state_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_STRUCTURE_FORM_STATE (pdf-to-html_structure_form_state_get_type ())
GType pdf-to-html_structure_table_scope_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_STRUCTURE_TABLE_SCOPE (pdf-to-html_structure_table_scope_get_type ())

/* enumerations from "pdf-to-html.h" */
GType pdf-to-html_error_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_ERROR (pdf-to-html_error_get_type ())
GType pdf-to-html_page_transition_type_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_PAGE_TRANSITION_TYPE (pdf-to-html_page_transition_type_get_type ())
GType pdf-to-html_page_transition_alignment_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_PAGE_TRANSITION_ALIGNMENT (pdf-to-html_page_transition_alignment_get_type ())
GType pdf-to-html_page_transition_direction_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_PAGE_TRANSITION_DIRECTION (pdf-to-html_page_transition_direction_get_type ())
GType pdf-to-html_selection_style_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_SELECTION_STYLE (pdf-to-html_selection_style_get_type ())
GType pdf-to-html_print_flags_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_PRINT_FLAGS (pdf-to-html_print_flags_get_type ())
GType pdf-to-html_find_flags_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_FIND_FLAGS (pdf-to-html_find_flags_get_type ())
GType pdf-to-html_backend_get_type (void) G_GNUC_CONST;
#define pdf-to-html_TYPE_BACKEND (pdf-to-html_backend_get_type ())
G_END_DECLS

#endif /* !pdf-to-html_ENUMS_H */

/* Generated data ends here */

